apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: nginx
spec:
  containers:
  - name: myapp-container
    image: k8s.gcr.io/echoserver:1.10  # Echo server on port 8080
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
