apiVersion: v1
kind: Pod
metadata:
  name: pod-with-static-pvc
spec:
  containers:
    - name: app
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ] # Just keeps the pod running
      volumeMounts:
        - mountPath: "/data"    # Inside the container
          name: storage-volume
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: static-pvc   # This links the PVC
